//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat15
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ключ.
    /// </summary>
    // *** Start programmer edit section *** (Ключ CustomAttributes)

    // *** End programmer edit section *** (Ключ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлючE", new string[] {
            "СгенКлюч as \'Сген ключ\'",
            "Уведомление as \'Уведомление\'",
            "Номер as \'Номер\'",
            "ФИО as \'ФИО\'",
            "Посылка as \'Посылка\'",
            "Посылка.Номер as \'Номер\'",
            "Пользователь as \'Пользователь\'",
            "Пользователь.ФИО as \'ФИО\'",
            "Хранение as \'Хранение\'",
            "Хранение.Продления as \'Продления\'"}, Hidden=new string[] {
            "Посылка.Номер",
            "Пользователь.ФИО",
            "Хранение.Продления"})]
    [MasterViewDefineAttribute("КлючE", "Посылка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("КлючE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("КлючE", "Хранение", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Продления")]
    [View("КлючL", new string[] {
            "СгенКлюч as \'Сген ключ\'",
            "Уведомление as \'Уведомление\'",
            "Номер as \'Номер\'",
            "ФИО as \'ФИО\'",
            "Посылка.Номер as \'Номер\'",
            "Пользователь.ФИО as \'ФИО\'",
            "Хранение.Продления as \'Продления\'"})]
    public class Ключ : IIS.Postamat15.Уведомление
    {
        
        private IIS.Postamat15.Посылка fПосылка;
        
        private IIS.Postamat15.Пользователь fПользователь;
        
        // *** Start programmer edit section *** (Ключ CustomMembers)

        // *** End programmer edit section *** (Ключ CustomMembers)

        
        /// <summary>
        /// СгенКлюч.
        /// </summary>
        // *** Start programmer edit section *** (Ключ.СгенКлюч CustomAttributes)

        // *** End programmer edit section *** (Ключ.СгенКлюч CustomAttributes)
        public override int СгенКлюч
        {
            get
            {
                // *** Start programmer edit section *** (Ключ.СгенКлюч Get start)

                // *** End programmer edit section *** (Ключ.СгенКлюч Get start)
                int result = base.СгенКлюч;
                // *** Start programmer edit section *** (Ключ.СгенКлюч Get end)

                // *** End programmer edit section *** (Ключ.СгенКлюч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ключ.СгенКлюч Set start)

                // *** End programmer edit section *** (Ключ.СгенКлюч Set start)
                base.СгенКлюч = value;
                // *** Start programmer edit section *** (Ключ.СгенКлюч Set end)

                // *** End programmer edit section *** (Ключ.СгенКлюч Set end)
            }
        }
        
        /// <summary>
        /// Ключ.
        /// </summary>
        // *** Start programmer edit section *** (Ключ.Пользователь CustomAttributes)

        // *** End programmer edit section *** (Ключ.Пользователь CustomAttributes)
        [PropertyStorage(new string[] {
                "Пользователь"})]
        [NotNull()]
        public virtual IIS.Postamat15.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (Ключ.Пользователь Get start)

                // *** End programmer edit section *** (Ключ.Пользователь Get start)
                IIS.Postamat15.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (Ключ.Пользователь Get end)

                // *** End programmer edit section *** (Ключ.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ключ.Пользователь Set start)

                // *** End programmer edit section *** (Ключ.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (Ключ.Пользователь Set end)

                // *** End programmer edit section *** (Ключ.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// Ключ.
        /// </summary>
        // *** Start programmer edit section *** (Ключ.Посылка CustomAttributes)

        // *** End programmer edit section *** (Ключ.Посылка CustomAttributes)
        [PropertyStorage(new string[] {
                "Посылка"})]
        [NotNull()]
        public virtual IIS.Postamat15.Посылка Посылка
        {
            get
            {
                // *** Start programmer edit section *** (Ключ.Посылка Get start)

                // *** End programmer edit section *** (Ключ.Посылка Get start)
                IIS.Postamat15.Посылка result = this.fПосылка;
                // *** Start programmer edit section *** (Ключ.Посылка Get end)

                // *** End programmer edit section *** (Ключ.Посылка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ключ.Посылка Set start)

                // *** End programmer edit section *** (Ключ.Посылка Set start)
                this.fПосылка = value;
                // *** Start programmer edit section *** (Ключ.Посылка Set end)

                // *** End programmer edit section *** (Ключ.Посылка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлючE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлючE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлючE", typeof(IIS.Postamat15.Ключ));
                }
            }
            
            /// <summary>
            /// "КлючL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлючL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлючL", typeof(IIS.Postamat15.Ключ));
                }
            }
        }
    }
}
