//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat15
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Постамат.
    /// </summary>
    // *** Start programmer edit section *** (Постамат CustomAttributes)

    // *** End programmer edit section *** (Постамат CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПостаматE", new string[] {
            "Номер as \'Номер\'",
            "Адрес as \'Адрес\'",
            "Статус as \'Статус\'"})]
    [AssociatedDetailViewAttribute("ПостаматE", "РегистрХран", "РегистрХранE", true, "", "Регистр хран", true, new string[] {
            ""})]
    [View("ПостаматL", new string[] {
            "Номер as \'Номер\'",
            "Адрес as \'Адрес\'",
            "Статус as \'Статус\'"})]
    public class Постамат : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fАдрес;
        
        private IIS.Postamat15.Статусы fСтатус;
        
        private IIS.Postamat15.DetailArrayOfРегистрХран fРегистрХран;
        
        // *** Start programmer edit section *** (Постамат CustomMembers)

        // *** End programmer edit section *** (Постамат CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Адрес CustomAttributes)

        // *** End programmer edit section *** (Постамат.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Адрес Get start)

                // *** End programmer edit section *** (Постамат.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Постамат.Адрес Get end)

                // *** End programmer edit section *** (Постамат.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Адрес Set start)

                // *** End programmer edit section *** (Постамат.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Постамат.Адрес Set end)

                // *** End programmer edit section *** (Постамат.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Номер CustomAttributes)

        // *** End programmer edit section *** (Постамат.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Номер Get start)

                // *** End programmer edit section *** (Постамат.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Постамат.Номер Get end)

                // *** End programmer edit section *** (Постамат.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Номер Set start)

                // *** End programmer edit section *** (Постамат.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Постамат.Номер Set end)

                // *** End programmer edit section *** (Постамат.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Статус CustomAttributes)

        // *** End programmer edit section *** (Постамат.Статус CustomAttributes)
        public virtual IIS.Postamat15.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Статус Get start)

                // *** End programmer edit section *** (Постамат.Статус Get start)
                IIS.Postamat15.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (Постамат.Статус Get end)

                // *** End programmer edit section *** (Постамат.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Статус Set start)

                // *** End programmer edit section *** (Постамат.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Постамат.Статус Set end)

                // *** End programmer edit section *** (Постамат.Статус Set end)
            }
        }
        
        /// <summary>
        /// Постамат.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.РегистрХран CustomAttributes)

        // *** End programmer edit section *** (Постамат.РегистрХран CustomAttributes)
        public virtual IIS.Postamat15.DetailArrayOfРегистрХран РегистрХран
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.РегистрХран Get start)

                // *** End programmer edit section *** (Постамат.РегистрХран Get start)
                if ((this.fРегистрХран == null))
                {
                    this.fРегистрХран = new IIS.Postamat15.DetailArrayOfРегистрХран(this);
                }
                IIS.Postamat15.DetailArrayOfРегистрХран result = this.fРегистрХран;
                // *** Start programmer edit section *** (Постамат.РегистрХран Get end)

                // *** End programmer edit section *** (Постамат.РегистрХран Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.РегистрХран Set start)

                // *** End programmer edit section *** (Постамат.РегистрХран Set start)
                this.fРегистрХран = value;
                // *** Start programmer edit section *** (Постамат.РегистрХран Set end)

                // *** End programmer edit section *** (Постамат.РегистрХран Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПостаматE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПостаматE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПостаматE", typeof(IIS.Postamat15.Постамат));
                }
            }
            
            /// <summary>
            /// "ПостаматL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПостаматL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПостаматL", typeof(IIS.Postamat15.Постамат));
                }
            }
        }
    }
}
